# : Manager [[[

[mgr]
cwd = { fg = "#dee3e6" }

# Tab
tab_active = { fg = "#003641", bg = "#85d1e8", bold = true }
tab_inactive = { fg = "#b0ecff", bg = "#001f27" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7880ff", bg = "#7880ff" }
marker_cut = { fg = "#dee0ff", bg = "#dee0ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c0c4eb", bg = "#c0c4eb" }

# Count
count_copied = { fg = "#141937", bg = "#dee0ff" }
count_cut = { fg = "#141937", bg = "#dee0ff" }
count_selected = { fg = "#003641", bg = "#c0c4eb" }

# Border
border_symbol = "│"
border_style  = { fg = "#85d1e8" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#003641", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#85d1e8", fg = "#003641", bold = true }
normal_alt  = { bg = "#40484b", fg = "#bfc8cb" }

# Select mode
select_main = { bg = "#b2cbd3", fg = "#1d343a", bold = true }
select_alt  = { bg = "#40484b", fg = "#bfc8cb" }

# Unset mode
unset_main = { bg = "#c0c4eb", fg = "#292e4d", bold = true }
unset_alt  = { bg = "#40484b", fg = "#bfc8cb" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#85d1e8", bg = "#343a3c" }
progress_error = { fg = "#ffb4ab", bg = "#343a3c" }

# Permissions
permissions_t = { fg = "#568796" }
permissions_w = { fg = "#4c57c6" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#4550ff" }
permissions_s = { fg = "#17c7ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#85d1e8" }
active = { fg = "#c0c4eb", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#85d1e8" }
value = { fg = "#dee3e6" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#85d1e8", bg = "#003641" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#85d1e8" }
title = {}
hovered = { fg = "#dee0ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3c" }
cand = { fg = "#85d1e8" }
rest = { fg = "#003641" }
desc = { fg = "#dee3e6" }
separator = " ▶ "
separator_style = { fg = "#dee3e6" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee3e6" }
run = { fg = "#dee3e6" }
footer = { fg = "#1d343a", bg = "#b2cbd3" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#c0c4eb" }
title_warn = { fg = "#85d1e8" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee3e6" },
    { name = "*/", fg = "#85d1e8" },
]

# : ]]]